### 1️⃣ Introduction to NumPy

In [3]:
import numpy as np

In [4]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


### Check dimension

In [5]:
print(a.ndim)

1


### Check datatype

In [6]:
print(a.dtype)

int64


In [1]:
import numpy as np

# Python list
list1 = [1, 2, 3, 4]
list2 = [5, 6, 7, 8]

# NumPy arrays
arr1 = np.array(list1)
arr2 = np.array(list2)

print("List Addition:", [list1[i] + list2[i] for i in range(len(list1))])
print("NumPy Addition:", arr1 + arr2)

List Addition: [6, 8, 10, 12]
NumPy Addition: [ 6  8 10 12]


### Important Array Attributes

In [8]:
b = np.array([[1,2,3],[4,5,6]])

print(b.shape)
print(b.size)
print(b.ndim)
print(b.dtype)

(2, 3)
6
2
int64


### 2️⃣ Creating NumPy Arrays

### 📌 1D Array

In [2]:
import numpy as np

arr = np.array([10, 20, 30, 40])
print(arr)

[10 20 30 40]


### 📌 2D Array (Matrix)

In [4]:
arr2 = np.array([ [1, 2, 3], [4, 5, 6] ])

print(arr2)

[[1 2 3]
 [4 5 6]]


### 📌 Special Array Functions

In [10]:
c = np.zeros((2,3))  # it returns array of zero
print(c)

[[0. 0. 0.]
 [0. 0. 0.]]


In [11]:
d = np.ones((3,3))   
print(d)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [17]:
e = np.eye(3) # it will create an identity matrix
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
f = np.arange(1, 10, 2)  # arange() = it returns directly an array . Whereas Range() returns a list
print(f)  # arange(start,stop,step) = simialr to range()

[1 3 5 7 9]


In [8]:
g = np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [13]:
#  empty() - Creates empty array
h = np.empty((2,3))
print(h)

[[0. 0. 0.]
 [0. 0. 0.]]


In [15]:
### np.full() is a NumPy function used to create a new array of a specified shape and fill it with a given constant value.
### np.full(shape, fill_value, dtype=None)

i = np.full((2,2),7)
print(i)

# 1️⃣ np.full - A NumPy function that creates a new array and fills every element with the same value.

# 2️⃣ (2,2) - This represents the shape of the array.

# 2 rows

# 2 columns

# So the array will be a 2 × 2 matrix.

# 3️⃣ 7 - This is the value that will fill every position in the array.

[[7 7]
 [7 7]]


In [16]:
j = np.full((3,3),5)
print(j)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [6]:
dtype_change = np.array([1,2,3,4] , dtype = 'float64')
print(dtype_change)
print(dtype_change.dtype)

[1. 2. 3. 4.]
float64


In [8]:
arar = np.array(range(2,20,2))
print(arar)

[ 2  4  6  8 10 12 14 16 18]


### ACCESSING ELEMENTS FROM ARRAY

In [9]:
print(arar[-3])

14


In [16]:
crcr = np.array([[1,2,3],
              [4,5,6]])

print(crcr[0,1])

2


In [11]:
# accessing multiple elements from the array this can be done by giving list of multiple indexes from the array which we want to print
print(arar[[1,2,3,4]])

[ 4  6  8 10]


### Reshaping array

In [12]:
brbr = np.arange(6)
print(brbr)

[0 1 2 3 4 5]


In [13]:
brbr.reshape((2,3))  # it will reshape the array into given dimension reshape(rows,column) 

array([[0, 1, 2],
       [3, 4, 5]])

In [14]:
brbr

array([0, 1, 2, 3, 4, 5])

In [15]:
brbr.reshape(2)

ValueError: cannot reshape array of size 6 into shape (2,)

### Array Slicing

In [17]:
drdr = np.array([10,20,30,40,50])

print(drdr[1:4])

[20 30 40]


### Boolean Indexing

In [19]:
er = np.array([1,2,3,4,5])

print(er[er>3])

[4 5]


### ARRAY OPERATIONS = ALL THE MATHEMATICAL OPERATIONS LIKE +,-,*,/ CAN BE EASILY DONE ON ARRAY

### Mathematical Functions

In [20]:
print(er)

[1 2 3 4 5]


In [22]:
# 1. sum()

sum = np.sum(er)
print(sum)

15


In [23]:
# 2. mean()

mean = np.mean(er)
print(mean)

3.0


In [28]:
# 3. median()

median = np.median(er)
print(median)

3.0


In [29]:
# 4. std() = Standard deviation

std = np.std(er)
print(std)

1.4142135623730951


In [30]:
# 5. var() = Variance

variance = np.var(er)
print(variance)

2.0


In [32]:
# 6. min() = minimum of the array

min_er = np.min(er)
print(min_er)

1


# RANDOM MODULE IN PYTHON

### 1️⃣ random.random() - Returns a random floating number between 0 and 1.

In [1]:
import random

In [3]:
print(random.random())

0.3689433760619085


### 2️⃣ random.randint() - Returns a random integer between two numbers (inclusive).

In [6]:
print(random.randint(1,10)) 
# Range - a ≤ value ≤ b

6


### 3️⃣ random.randrange() - Returns a random number from a range.

In [7]:
print(random.randrange(1,10))
# Range - start ≤ value < stop
# Syntax - random.randrange(start, stop, step)

2


### 4️⃣ random.choice() - Selects one random element from a sequence.

In [8]:
# Syntax - random.choice(sequence)
colors = ["red","blue","green"]

print(random.choice(colors))

green


### 5️⃣ random.choices() - Returns multiple random elements with replacement.

In [12]:
data = [1,2,3,4]

print(random.choices(data, k=2))

# with replacement means DUPLICATES ARE ALLOWED

[4, 1]


### 6️⃣ random.sample() - Returns multiple random elements without replacement.

In [13]:
data = [1,2,3,4,5]

print(random.sample(data,3))

# without replacement means DUPLICATES ARE NOT ALLOWED

[3, 5, 2]


### 7️⃣ random.shuffle() - Randomly shuffles elements of a list.

In [16]:
data = [1,2,3,4]

random.shuffle(data)

print(data)

# it changes the original list
# ⚠ Works only with lists

[1, 3, 2, 4]


### 8️⃣ random.uniform() - Returns a random floating number between two values.

In [18]:
print(random.uniform(5,10))

# Range - 5 ≤ value ≤ 10

6.526688316662008


### 9️⃣ numpy.random (VERY IMPORTANT for Data Analytics)

In [19]:
import numpy as np

### 1️⃣ np.random.rand() - Generates random numbers between 0 and 1

In [20]:
np.random.rand(3)

array([0.6321375 , 0.55633007, 0.79026979])

In [21]:
print(np.random.rand(2,3))

[[0.41900043 0.00470014 0.02327156]
 [0.9284148  0.48555981 0.51022914]]


### 2️⃣ np.random.randint() 

In [9]:
print(np.random.randint(1,10)) 
 # here we have not given how many values we want so by default it will print only 1 random value from the range

5


In [7]:
ages = np.random.randint(18,60,100)
print(ages)

# it will print random 100 values from the range of 18 and 60

[46 50 25 41 22 40 32 53 38 55 21 32 55 32 52 39 32 48 35 56 28 41 19 46
 28 29 19 36 52 29 28 54 24 21 52 39 34 57 36 39 41 37 25 34 21 56 45 50
 41 52 43 34 36 37 50 42 58 26 40 29 26 42 58 44 34 46 44 48 19 45 20 42
 31 31 43 58 24 57 55 35 24 56 55 59 48 20 54 28 43 36 50 34 40 58 49 56
 22 41 57 18]


In [23]:
print(np.random.randint(1,10,5)) # will give an array of 5 element and the number will be random from 1 to 10

[3 3 8 8 2]


### 3️⃣ np.random.choice()  - Random selection from array.

In [24]:
print(np.random.choice([10,20,30,40],3))

[30 40 40]


### 4️⃣ np.random.shuffle() - Shuffle array.

In [25]:
data = np.array([1,2,3,4])

np.random.shuffle(data)

print(data)

[3 1 2 4]


In [2]:
import numpy as np

np.random.seed(10)

print(np.random.randint(1,100))

10


In [5]:
probability = np.random.rand(100)