### 1️⃣ Introduction to NumPy

 If we go in depth is why NUMPY is faster than PYTHON :-
 1. Then the main point is NUMPY runs on C language internally all the operations in NUMPY is done in C which is compiled language.
 2. And second main point is in PYTHON elements in the LIST are not store in continuity which means for ex; ls = [1,2,3,4]

So, here in 'ls' the element '1' can be stored at let say memory address of 3000 but it is not necessary that '2' will be stored
at the 3001 address it can be at the any other address . Hence it becomes difficult for python to locate them in the Static memory

Whereas in NUMPY which runs on the C lang the elements of the array are stored in continuity.
Ex: a = [1 2 3 4] here if element '1' is stored at address = 3000 THEN element '2' will be at address = 3001
HEnce it becomes easier for the NUMPY to access the elements

In [3]:
# This example simply describe the power and usage of 'numpy'
# It's simply does all the calculations on its own.
import numpy as np
ls = [1,2,3,4,5]
print(ls*2)

ar = np.array(ls)
print(ar*2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]


In [1]:
import numpy as np

In [4]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


### Check dimension

In [5]:
print(a.ndim)

1


### Check datatype

In [6]:
print(a.dtype)

int64


In [1]:
import numpy as np

# Python list
list1 = [1, 2, 3, 4]
list2 = [5, 6, 7, 8]

# NumPy arrays
arr1 = np.array(list1)
arr2 = np.array(list2)

print("List Addition:", [list1[i] + list2[i] for i in range(len(list1))])
print("NumPy Addition:", arr1 + arr2)

List Addition: [6, 8, 10, 12]
NumPy Addition: [ 6  8 10 12]


### Important Array Attributes

In [8]:
b = np.array([[1,2,3],[4,5,6]])

print(b.shape)
print(b.size)
print(b.ndim)
print(b.dtype)

(2, 3)
6
2
int64


### 2️⃣ Creating NumPy Arrays

### 📌 1D Array

In [2]:
import numpy as np

arr = np.array([10, 20, 30, 40])
print(arr)

[10 20 30 40]


### 📌 2D Array (Matrix)

In [2]:
arr2 = np.array([ [1, 2, 3], [4, 5, 6] ])

print(arr2)

[[1 2 3]
 [4 5 6]]


In [3]:
print(arr2.shape)   # rows, columns
print(arr2.ndim)    # dimension
print(arr2.size)    # total elements

(2, 3)
2
6


In [4]:
# Access row
print(arr2[0])

[1 2 3]


In [5]:
# Access element
print(arr2[1,2])

6


In [6]:
# Access Full Column
print(arr2[:,0])

[1 4]


In [7]:
# Access Full Row
print(arr2[1,:])

[4 5 6]


In [8]:
# Slicing in 2D Array
# array[row_start:row_end , col_start:col_end]
print(arr2[0:2 , 1:3])

[[2 3]
 [5 6]]


### 📌 Special Array Functions

In [10]:
c = np.zeros((2,3))  # it returns array of zero
print(c)

[[0. 0. 0.]
 [0. 0. 0.]]


In [11]:
d = np.ones((3,3))   
print(d)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [17]:
e = np.eye(3) # it will create an identity matrix
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
f = np.arange(1, 10, 2)  # arange() = it returns directly an array . Whereas Range() returns a list
print(f)  # arange(start,stop,step) = simialr to range()

[1 3 5 7 9]


In [8]:
g = np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [13]:
#  empty() - Creates empty array
h = np.empty((2,3))
print(h)

[[0. 0. 0.]
 [0. 0. 0.]]


In [15]:
### np.full() is a NumPy function used to create a new array of a specified shape and fill it with a given constant value.
### np.full(shape, fill_value, dtype=None)

i = np.full((2,2),7)
print(i)

# 1️⃣ np.full - A NumPy function that creates a new array and fills every element with the same value.

# 2️⃣ (2,2) - This represents the shape of the array.

# 2 rows

# 2 columns

# So the array will be a 2 × 2 matrix.

# 3️⃣ 7 - This is the value that will fill every position in the array.

[[7 7]
 [7 7]]


In [16]:
j = np.full((3,3),5)
print(j)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [6]:
dtype_change = np.array([1,2,3,4] , dtype = 'float64')
print(dtype_change)
print(dtype_change.dtype)

[1. 2. 3. 4.]
float64


In [8]:
arar = np.array(range(2,20,2))
print(arar)

[ 2  4  6  8 10 12 14 16 18]


### ACCESSING ELEMENTS FROM ARRAY

In [9]:
print(arar[-3])

14


In [16]:
crcr = np.array([[1,2,3],
              [4,5,6]])

print(crcr[0,1])

2


In [11]:
# accessing multiple elements from the array this can be done by giving list of multiple indexes from the array which we want to print
print(arar[[1,2,3,4]])

[ 4  6  8 10]


### Reshaping array

In [5]:
brbr = np.arange(6)
print(brbr)

[0 1 2 3 4 5]


In [13]:
brbr.reshape((2,3))  # it will reshape the array into given dimension reshape(rows,column) 

array([[0, 1, 2],
       [3, 4, 5]])

In [14]:
brbr

array([0, 1, 2, 3, 4, 5])

In [15]:
brbr.reshape(2)

ValueError: cannot reshape array of size 6 into shape (2,)

In [9]:
# giving negative values in reshape
brbr.reshape((2,-1))

# Here it will divide the size of array by the row value given to the reshape() function and will produce that many column

array([[0, 1, 2],
       [3, 4, 5]])

In [10]:
brbr.reshape((-1,2)) # here it will fix the no. of columns i.e. 2 and will calc the row value by using col value

array([[0, 1],
       [2, 3],
       [4, 5]])

### Array Slicing

In [17]:
drdr = np.array([10,20,30,40,50])

print(drdr[1:4])

[20 30 40]


### Boolean Indexing

In [19]:
er = np.array([1,2,3,4,5])

print(er[er>3])

[4 5]


## Masking and Vectorization

In [12]:
erer = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)

mask = (erer >= 5)
print(mask)

[[False False False]
 [False  True  True]
 [ True  True  True]]


### ARRAY OPERATIONS = ALL THE MATHEMATICAL OPERATIONS LIKE +,-,*,/ CAN BE EASILY DONE ON ARRAY

### Mathematical Functions

In [20]:
print(er)

[1 2 3 4 5]


In [22]:
# 1. sum()

sum = np.sum(er)
print(sum)

15


In [23]:
# 2. mean()

mean = np.mean(er)
print(mean)

3.0


In [28]:
# 3. median()

median = np.median(er)
print(median)

3.0


In [29]:
# 4. std() = Standard deviation

std = np.std(er)
print(std)

1.4142135623730951


In [30]:
# 5. var() = Variance

variance = np.var(er)
print(variance)

2.0


In [32]:
# 6. min() = minimum of the array

min_er = np.min(er)
print(min_er)

1


# RANDOM MODULE IN PYTHON

### 1️⃣ random.random() - Returns a random floating number between 0 and 1.

In [1]:
import random

In [3]:
print(random.random())

0.3689433760619085


### 2️⃣ random.randint() - Returns a random integer between two numbers (inclusive).

In [6]:
print(random.randint(1,10)) 
# Range - a ≤ value ≤ b

6


### 3️⃣ random.randrange() - Returns a random number from a range.

In [7]:
print(random.randrange(1,10))
# Range - start ≤ value < stop
# Syntax - random.randrange(start, stop, step)

2


### 4️⃣ random.choice() - Selects one random element from a sequence.

In [8]:
# Syntax - random.choice(sequence)
colors = ["red","blue","green"]

print(random.choice(colors))

green


### 5️⃣ random.choices() - Returns multiple random elements with replacement.

In [12]:
data = [1,2,3,4]

print(random.choices(data, k=2))

# with replacement means DUPLICATES ARE ALLOWED

[4, 1]


### 6️⃣ random.sample() - Returns multiple random elements without replacement.

In [13]:
data = [1,2,3,4,5]

print(random.sample(data,3))

# without replacement means DUPLICATES ARE NOT ALLOWED

[3, 5, 2]


### 7️⃣ random.shuffle() - Randomly shuffles elements of a list.

In [16]:
data = [1,2,3,4]

random.shuffle(data)

print(data)

# it changes the original list
# ⚠ Works only with lists

[1, 3, 2, 4]


### 8️⃣ random.uniform() - Returns a random floating number between two values.

In [18]:
print(random.uniform(5,10))

# Range - 5 ≤ value ≤ 10

6.526688316662008


### 9️⃣ numpy.random (VERY IMPORTANT for Data Analytics)

In [2]:
import numpy as np

### 1️⃣ np.random.rand() - Generates random numbers between 0 and 1

In [20]:
np.random.rand(3)

array([0.6321375 , 0.55633007, 0.79026979])

In [21]:
print(np.random.rand(2,3))

[[0.41900043 0.00470014 0.02327156]
 [0.9284148  0.48555981 0.51022914]]


### 2️⃣ np.random.randint() 
It is np.random sub-module method which return can single random value , 1D array of random values 2D array of random values as per the given range. 

Syntax : np.random.randint(start, stop, size = shape of array)

In [9]:
print(np.random.randint(1,10)) 
 # here we have not given how many values we want so by default it will print only 1 random value from the range

5


In [3]:
ages = np.random.randint(18,60,100)
print(ages)

# it will print random 100 values from the range of 18 and 60 in an array

[26 59 36 58 45 41 56 59 38 22 53 25 51 32 53 25 53 20 29 38 41 42 55 44
 24 24 25 29 55 22 34 33 54 51 51 51 43 25 40 53 19 41 55 49 51 42 23 46
 29 58 20 41 31 44 59 34 35 54 23 39 39 54 31 58 41 34 59 48 39 53 58 49
 36 32 59 37 18 57 38 37 59 48 32 58 30 48 56 52 47 28 22 45 45 50 37 31
 51 23 56 38]


In [8]:
print(np.random.randint(1,100,size = (2,5)))

[[85 34 36 56 27]
 [11 94 62 37  4]]


In [12]:
# rando.seed(state) = seed() method will create a specific state for an array which means the value 
# which has been generated by random.randint() for that STATE will be same and it will not change no matter how many time we run it
np.random.seed(7)
a=np.random.randint(1,101,size=(2,5))
print(a)

[[48 69 26 68 84]
 [24 93 58 15 24]]


In [4]:
print(np.random.randint(1,10,5)) # will give an array of 5 element and the number will be random from 1 to 10

[8 7 7 4 2]


### 3️⃣ np.random.choice()  - Random selection from array.

In [24]:
print(np.random.choice([10,20,30,40],3))

[30 40 40]


### 4️⃣ np.random.shuffle() - Shuffle array.

In [25]:
data = np.array([1,2,3,4])

np.random.shuffle(data)

print(data)

[3 1 2 4]


In [5]:
import numpy as np

np.random.seed(10)

print(np.random.randint(1,100))

10


In [4]:
probability = np.random.rand(10)
print(probability)

[0.62485473 0.90693655 0.42981661 0.4874485  0.65313407 0.87439162
 0.90917372 0.29285895 0.79409948 0.59997821]


### BOOLEAN INDEXING

In [6]:
bool_indexing = np.arange(1,6)
print(bool_indexing)

[1 2 3 4 5]


In [7]:
print(bool_indexing[[True,False,True,False,False]])

[1 3]


In [10]:
print(bool_indexing[bool_indexing > 2 ])  # [bool_indexing > 2] = This will give [False,False,True,True,True]

[3 4 5]


In [12]:
# We want to print positive even elements from an array.
print(bool_indexing[(bool_indexing > 0) & (bool_indexing % 2 == 0)])

[2 4]


In [13]:
# Print negative odd elements
print(bool_indexing[(bool_indexing < 0 ) & (bool_indexing % 2 != 0)])

[]


In [13]:
data = np.arange(1,7).reshape(3,2)
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [14]:
sum_col = np.mean(data[:,0])
print(sum_col)

3.0


In [15]:
max_dt = np.max(data[:,1])
print(max_dt)

6


In [20]:
dt = np.arange(20,29).reshape(3,3)
print(dt)

[[20 21 22]
 [23 24 25]
 [26 27 28]]


In [21]:
print(dt[dt[:,1] > 25])

[[26 27 28]]


In [22]:
print(dt[:,1] + 5)

[26 29 32]


In [24]:
print(dt[ (dt[:,1] >= 22) & (dt[:,2] >= 22) ])

[[23 24 25]
 [26 27 28]]


## DATA TRANSFORMATIONS (USING WHERE AND SELECT)

## 1️⃣ np.where() — BASIC IDEA

In [2]:
arr6 = np.array([10, 20, 30, 40])

result = np.where(arr6 > 25, "High", "Low")

print(result)

['Low' 'Low' 'High' 'High']


In [5]:
arr7 = np.array([1,2,3,4,5])

result7 = np.where(arr7 % 2 == 0, 0, arr7) # here we are replcing even number with 0 and keeping odd numbers as it is

print(result7)

[1 0 3 0 5]


In [7]:
# MODIFY EXISTING ARRAY
arr8 = np.array([10,20,30,40])

arr8 = np.where(arr8 > 20, arr8 * 2, arr8)

print(arr8)

[10 20 60 80]


In [9]:
# MULTIPLE CONDITIONS USING WHERE (NESTED) - NOT RECOMMENDED
arr9 = np.array([10,20,30,40,50])

result9 = np.where(
            arr9 < 20, "Low",
            np.where(arr9 < 40, "Medium", "High")
          )

print(result9)

['Low' 'Medium' 'Medium' 'High' 'High']


In [11]:
arr10 = np.array([10,20,30,40])

np.where(arr10 > 25)
# it will return an array of indexes which will match this criteria

(array([2, 3]),)

In [12]:
salary = np.array([20000,35000,50000,15000])

grade = np.where(salary > 30000, "Good", "Bad")

print(grade)

['Bad' 'Good' 'Good' 'Bad']


# 🔷 np.select() — MULTIPLE CONDITIONS

In [14]:
marks = np.array([35, 55, 75, 90])

conditions = [
    marks < 40,
    marks < 70,
    marks >= 70
]

choices = ["Fail", "Pass", "Distinction"]

result11 = np.select(conditions, choices, default="Unknown")

print(result11)

['Fail' 'Pass' 'Distinction' 'Distinction']


In [16]:
age = np.array([12, 18, 25, 60])

conditions = [
    age < 18,
    age < 60,
    age >= 60
]

choices = [
    "Child",
    "Adult",
    "Senior"
]

result12 = np.select(conditions, choices,default="Unknown")

print(result12)

['Child' 'Adult' 'Adult' 'Senior']


In [18]:
purchase = np.array([100,500,2000,7000])

conditions = [
    purchase < 500,
    purchase < 3000,
    purchase >= 3000
]

choices = [
    "Low",
    "Medium",
    "High"
]

print(np.select(conditions, choices,default="Unknown"))

['Low' 'Medium' 'Medium' 'High']


In [20]:
marks = np.array([45,65,85])

conditions = [
    marks < 50,
    marks < 80,
    marks >= 80
]

choices = ["C","B","A"]

print(np.select(conditions, choices,default=""))

['C' 'B' 'A']


### QUICK REVISION